Mobile skeleton
chumaachike/mobile-portfolio pull request #1
Opened 2022-03-17 22:17 UTC by chumaachike

Created the home page of the mobile version of the portfolio design using flexbox.

2022-03-17 23:42 UTC, phelian23 requested changes
Hi @chumaachike, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- All linter checks are passing ✔️
- Descriptive commits and correct use of the Git Flow 🔥
- Descriptive PR ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 23:42 UTC, phelian23 commented on index.html
> +      <div class="name">Achike Chuma</div>
- [ ] In this case, this element is supposed to be the logo. kindly use an `<a>` tag to wrap the logo instead of a `div` tag.

2022-03-17 23:42 UTC, phelian23 commented on index.html
> +      <img src="images/Enabled.png" alt="hamburger navigation logo" />
- [ ] It's a good idea to use the right semantic tag on the page whenever possible. Please wrap the hamburger icon with a `nav` tag.
You can read more on semantic tag [here](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-03-17 23:42 UTC, phelian23 commented on index.html
> +      </div>
- [ ] It's a good idea to use the right semantic tag on the page whenever possible as it improves webpage SEO. Kindly wrap this section in a `section` tag.
You can read more on semantic tag [here](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-03-17 23:42 UTC, phelian23 commented on index.html
> +      </div>
- [ ] Kindly wrap all social links with `<ul>` and `<li>` tags, eg.:

``` markup
<ul>
  <li>
    <a><img src="images/mouse-icon.png" alt="mouse icon"></a>
  </li>
</ul>
```

2022-03-17 23:42 UTC, phelian23 commented on index.html
> +        />
- [ ] Kindly implement this image as a background image in your CSS file, as it is a decoration, and it's a good practice to make a decorations background image.

2022-03-17 23:42 UTC, phelian23 commented on styles/style.css
> +h1 {
- [ ] Kindly make sure that your design match the Figma template design as much as possible (e.g. font, colors, images, tests, margins)
Your design
![Capture](https://user-images.githubusercontent.com/85095702/158910900-6427b211-8a9d-405d-9751-4a3b7f8fbc45.PNG)

Figma template
![figma](https://user-images.githubusercontent.com/85095702/158910955-ad8b7025-0b48-4db3-85f8-045c03aa28a4.PNG)

2022-03-17 23:42 UTC, phelian23 commented on styles/style.css
> +}
- [ ] Instead of using display: flex; multiple times, kindly create a class say

``` css
.flex {
  display: flex;
}
```
and use the class in the HTML element that needs it. This will help your code to follow the DRY rule.

2022-03-18 21:11 UTC, xtrahuman requested changes
Hello @chumaachike , 

Amazing job so far, Keep up the positive energy 👍 😄 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

**_Kindly note that it is important to create descriptive commit messages_**

![image](https://user-images.githubusercontent.com/43564324/158876088-ebd2a4dc-a738-46bc-a796-c8268519cc96.png)

 ## Required Changes ♻️
_Kindly Check the comments under the review._ 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 21:11 UTC, xtrahuman commented on styles/style.css
>  }
Kindly Make sure the h1 styling matches with the given template please check [design requirements](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) and replicate it as close as possible, the ability to replicate design perfectly is one of the great skills of a developer

2022-03-19 02:51 UTC, nicupop729 reviewed
# STATUS: APPROVED :green_circle: :clap: 

Hi @chumaachike, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**I really appreciate your hard work over this week!!** :clap: 
**Please take into consideration to not use fixed width and height for the big elements in your design**
Take the figma design as an example of how your display should look, but don't do the mistake to copy the heights and widths from there when is very important for us to implement a responsive design, which will take the whole screen of the device, even if is a mobile or a desktop.
Instead, it's better to take advantage of flexbox and grid to design our app.


![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 16:15 UTC, merged